<?php

// Enforce type checking
declare(strict_types=1);

namespace App\Controllers;

use App\Models\Mail;
use Framework\Viewer;
use Framework\Exceptions\PageNotFoundException;
use Framework\Controller;
use Framework\Response;

/**
 * Controller for handling name-related actions.
 */
class MailTest extends Controller
{
    /**
     * Constructor.
     *
     * @param Name $model The name model
     */
    public function __construct(private Mail $mailer){}

   // Email test page
   public function sendEmailView(): Response
   {
        $this->response->appendBody($this->viewer->render("/mailtest/mailtest.php"));

        // Check if the request is a POST submission
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            // Define email content
            $to = $_POST['email'] ?? 'tugglem@rrjva.org'; // Replace with form input
            $subject = 'Test Email from MailTest Controller';
            $body = 'This is a test email generated by the MailTest controller.';

            // Send email using Mail model
            if ($this->mailer->sendBasicEmail($to, $subject, $body)) {
                $this->response->appendBody("<p>Email sent successfully to $to!</p>");
            } else {
                $this->response->appendBody("<p>Failed to send email to $to.</p>");
            }
        }
        
        return $this->response;
   }

}